[#324] Make sure the default container name is unique
nspcc-dev/neofs-s3-gw pull request #325
Opened 2022-01-20 13:43 UTC by KirillovDenis

closes #324 
Signed-off-by: Denis Kirillov <denis@nspcc.ru>

2022-01-20 14:50 UTC, masterSplinter01 approved these changes

2022-01-21 07:26 UTC, realloc requested changes
I'd suggest avoiding setting friendly names if the user didn't set it explicitly. That would cost more GAS and require more operations than accessing via CID later.

2022-01-21 08:21 UTC, realloc approved these changes
LGTM, didn't run

2022-01-21 12:38 UTC, masterSplinter01 approved these changes

2022-01-21 12:39 UTC, merged